### ISSUE TITLE
Promotion zap triggered customer email, but no Slack notification

### ISSUE THREAD

**Issue by jmarlow94** [animalzinc/animalzinc.github.io#2]
I tried promoting an article [(Airtable Link)](https://airtable.com/tblVd5ewTbNFwTzB2/viwnDkumo8ZsjaCEQ/recyMkiplHIyPsFHq) that had been categorized as Campaign Monitor on Inbound and Growth Hackers, added the two promotion records, then sent to Done.

The zap seems to have sent the email to the customer, but never made it to Slack

<img width="671" alt="screen shot 2017-04-06 at 4 46 03 pm" src="https://cloud.githubusercontent.com/assets/26981094/24774863/963719fa-1ae8-11e7-99be-fa45e5f0fc33.png">

**Comment by smalter** [comment]
@jmarlow94 the slack issue occurred because the email triggered immediately based on a timezone change to the createdDateTime field in Promotions in Airtable.

Previously, it was UTC and I changed it to US/Eastern. That changed the the calculation that checks whether time now (in UTC) is 1 hr ahead of createdDateTime. It was previously UTC to UTC, and my change made it Eastern to UTC. Because UTC is 4 hours ahead, createdDateTime plus 1 hr was always less than now which immediately triggered the customer notification emails.

When those emails went out, the article was marked as having customer notifications as sent and so the article was taken out of the Promotion view in Airtable so the slack notification wasn't sent.

this commit should fix the issue, as the time comparison is now happening in Airtable https://github.com/animalzinc/panther/commit/b3b34aca5f03b44cfe60d1c0cc0aa29e4326a22d

Let me know if you see this happen again.
